{"name": "Login to nopCommerce with valid parameters", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: DataTables warning: table id=average-order-report-grid - Ajax error. For more information about this error, please see http://datatables.net/tn/7\nMessage: unexpected alert open: {Alert text : DataTables warning: table id=average-order-report-grid - Ajax error. For more information about this error, please see http://datatables.net/tn/7}\n  (Session info: chrome=106.0.5249.119)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00D5DF13+2219795]\n\tOrdinal0 [0x00CF2841+1779777]\n\tOrdinal0 [0x00C0423D+803389]\n\tOrdinal0 [0x00C5EFFE+1175550]\n\tOrdinal0 [0x00C4E616+1107478]\n\tOrdinal0 [0x00C27F89+950153]\n\tOrdinal0 [0x00C28F56+954198]\n\tGetHandleVerifier [0x01052CB2+3040210]\n\tGetHandleVerifier [0x01042BB4+2974420]\n\tGetHandleVerifier [0x00DF6A0A+565546]\n\tGetHandleVerifier [0x00DF5680+560544]\n\tOrdinal0 [0x00CF9A5C+1808988]\n\tOrdinal0 [0x00CFE3A8+1827752]\n\tOrdinal0 [0x00CFE495+1827989]\n\tOrdinal0 [0x00D080A4+1867940]\n\tBaseThreadInitThunk [0x76157BA9+25]\n\tRtlInitializeExceptionChain [0x77C5BB3B+107]\n\tRtlClearBits [0x77C5BABF+191]\n\n", "trace": "  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\nopcommercesteps.py\", line 27, in dashboardpage\n    status=context.driver.title\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 453, in title\n    resp = self.execute(Command.GET_TITLE)\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 246, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n"}, "steps": [{"name": "Given Launch Chrome browser", "status": "passed", "start": 1666617100813, "stop": 1666617106665}, {"name": "When Open nopCommerce page", "status": "passed", "start": 1666617106668, "stop": 1666617109298}, {"name": "And Enter username \"admin@yourstore.com\" and password \"admin\"", "status": "passed", "start": 1666617109300, "stop": 1666617109982}, {"name": "And Click on login button", "status": "passed", "start": 1666617109982, "stop": 1666617115293}, {"name": "Then User must be successfully able to login to dashboard page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: DataTables warning: table id=average-order-report-grid - Ajax error. For more information about this error, please see http://datatables.net/tn/7\nMessage: unexpected alert open: {Alert text : DataTables warning: table id=average-order-report-grid - Ajax error. For more information about this error, please see http://datatables.net/tn/7}\n  (Session info: chrome=106.0.5249.119)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00D5DF13+2219795]\n\tOrdinal0 [0x00CF2841+1779777]\n\tOrdinal0 [0x00C0423D+803389]\n\tOrdinal0 [0x00C5EFFE+1175550]\n\tOrdinal0 [0x00C4E616+1107478]\n\tOrdinal0 [0x00C27F89+950153]\n\tOrdinal0 [0x00C28F56+954198]\n\tGetHandleVerifier [0x01052CB2+3040210]\n\tGetHandleVerifier [0x01042BB4+2974420]\n\tGetHandleVerifier [0x00DF6A0A+565546]\n\tGetHandleVerifier [0x00DF5680+560544]\n\tOrdinal0 [0x00CF9A5C+1808988]\n\tOrdinal0 [0x00CFE3A8+1827752]\n\tOrdinal0 [0x00CFE495+1827989]\n\tOrdinal0 [0x00D080A4+1867940]\n\tBaseThreadInitThunk [0x76157BA9+25]\n\tRtlInitializeExceptionChain [0x77C5BB3B+107]\n\tRtlClearBits [0x77C5BABF+191]\n\n", "trace": "  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\nopcommercesteps.py\", line 27, in dashboardpage\n    status=context.driver.title\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 453, in title\n    resp = self.execute(Command.GET_TITLE)\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 246, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n"}, "start": 1666617115293, "stop": 1666617115318}, {"name": "And Close browser", "status": "skipped", "start": 1666617115327, "stop": 1666617115327}], "start": 1666617100813, "stop": 1666617115327, "uuid": "4250a857-e844-4ce5-b05d-b70ebb13cb9d", "historyId": "e4e99d9b037112e94a0b386ed7229154", "fullName": "nopCommerce Login: Login to nopCommerce with valid parameters", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "nopCommerce Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}