{"name": "Login to nopCommerce with valid parameters", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00FFDF13+2219795]\n\tOrdinal0 [0x00F92841+1779777]\n\tOrdinal0 [0x00EA4100+803072]\n\tOrdinal0 [0x00EC7C6D+949357]\n\tOrdinal0 [0x00EC8F56+954198]\n\tGetHandleVerifier [0x012F2CB2+3040210]\n\tGetHandleVerifier [0x012E2BB4+2974420]\n\tGetHandleVerifier [0x01096A0A+565546]\n\tGetHandleVerifier [0x01095680+560544]\n\tOrdinal0 [0x00F99A5C+1808988]\n\tOrdinal0 [0x00F9E3A8+1827752]\n\tOrdinal0 [0x00F9E495+1827989]\n\tOrdinal0 [0x00FA80A4+1867940]\n\tBaseThreadInitThunk [0x76157BA9+25]\n\tRtlInitializeExceptionChain [0x77C5BB3B+107]\n\tRtlClearBits [0x77C5BABF+191]\n\n", "trace": "  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\nopcommercesteps.py\", line 40, in closebrowser\n    context.driver.close()\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 943, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Launch Chrome browser", "status": "passed", "start": 1666454789876, "stop": 1666454793997}, {"name": "When Open nopCommerce page", "status": "passed", "start": 1666454793997, "stop": 1666454795954}, {"name": "And Enter username \"admin@yourstore.com\" and password \"admin\"", "status": "passed", "start": 1666454795958, "stop": 1666454797297}, {"name": "And Click on login button", "status": "passed", "start": 1666454797297, "stop": 1666454802139}, {"name": "Then User must be successfully able to login to dashboard page", "status": "passed", "start": 1666454802139, "stop": 1666454802746}, {"name": "And Close browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00FFDF13+2219795]\n\tOrdinal0 [0x00F92841+1779777]\n\tOrdinal0 [0x00EA4100+803072]\n\tOrdinal0 [0x00EC7C6D+949357]\n\tOrdinal0 [0x00EC8F56+954198]\n\tGetHandleVerifier [0x012F2CB2+3040210]\n\tGetHandleVerifier [0x012E2BB4+2974420]\n\tGetHandleVerifier [0x01096A0A+565546]\n\tGetHandleVerifier [0x01095680+560544]\n\tOrdinal0 [0x00F99A5C+1808988]\n\tOrdinal0 [0x00F9E3A8+1827752]\n\tOrdinal0 [0x00F9E495+1827989]\n\tOrdinal0 [0x00FA80A4+1867940]\n\tBaseThreadInitThunk [0x76157BA9+25]\n\tRtlInitializeExceptionChain [0x77C5BB3B+107]\n\tRtlClearBits [0x77C5BABF+191]\n\n", "trace": "  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\nopcommercesteps.py\", line 40, in closebrowser\n    context.driver.close()\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 943, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Reka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1666454802746, "stop": 1666454802959}], "start": 1666454789870, "stop": 1666454802959, "uuid": "829d8bc6-cfe0-4c4f-a45e-cde2ae569045", "historyId": "e4e99d9b037112e94a0b386ed7229154", "fullName": "nopCommerce Login: Login to nopCommerce with valid parameters", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "nopCommerce Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}